### ISSUE TITLE
BUnch Input

### ISSUE THREAD

**Issue by miewan** [ArchitectingSoftware/Bunch#2]
I am running Bunch and it accept the input, but when I run it with same input in different machine, it said no input graph. Are there any reason why the same input is accepted by Bunch in one machine but not in other machine.

**Comment by ArchitectingSoftware** [comment]
Sorry to hear you are having problems.  Not sure why this would happen.  The code runs in the JVM so its exact same code across platforms and machines.  If you could reproduce it would be helpful.  You can also try running from source in a debugger to see what’s going on.

**Comment by miewan** [comment]
This is the output in the command prompt after I put the input. 

C:\Users\vm-user>java -jar C:\Users\vm-user\Desktop\Bunch-3.5.jar
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.String.substring(Unknown Source)
        at java.util.StringTokenizer.nextToken(Unknown Source)
        at bunch.DependencyFileParser.parse(DependencyFileParser.java:132)
        at bunch.BunchFrame.selectGraphFileButton_d_actionPerformed(BunchFrame.java:972)
        at bunch.BunchFrame_selectGraphFileButton_d_actionAdapter.actionPerformed(BunchFrame.java:2745)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

**Comment by ArchitectingSoftware** [comment]
See this:  https://stackoverflow.com/questions/4667483/how-is-the-default-max-java-heap-size-determined   Looks like your second machine does not have enough heap space based on how the JVM sets its defaults. You can override the default heap allocation using the Xmx flag.

**Comment by miewan** [comment]
Thank you so much. It works now.

**Comment by ArchitectingSoftware** [comment]
Glad to help. Thanks for using Bunch
